// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_watcher

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIndexer creates a new instance of MockIndexer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIndexer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIndexer {
	mock := &MockIndexer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIndexer is an autogenerated mock type for the Indexer type
type MockIndexer struct {
	mock.Mock
}

type MockIndexer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIndexer) EXPECT() *MockIndexer_Expecter {
	return &MockIndexer_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockIndexer
func (_mock *MockIndexer) Delete(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIndexer_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIndexer_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - path string
func (_e *MockIndexer_Expecter) Delete(path any) *MockIndexer_Delete_Call {
	return &MockIndexer_Delete_Call{Call: _e.mock.On("Delete", path)}
}

func (_c *MockIndexer_Delete_Call) Run(run func(path string)) *MockIndexer_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIndexer_Delete_Call) Return(err error) *MockIndexer_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIndexer_Delete_Call) RunAndReturn(run func(path string) error) *MockIndexer_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Index provides a mock function for the type MockIndexer
func (_mock *MockIndexer) Index(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIndexer_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type MockIndexer_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
//   - path string
func (_e *MockIndexer_Expecter) Index(path any) *MockIndexer_Index_Call {
	return &MockIndexer_Index_Call{Call: _e.mock.On("Index", path)}
}

func (_c *MockIndexer_Index_Call) Run(run func(path string)) *MockIndexer_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIndexer_Index_Call) Return(err error) *MockIndexer_Index_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIndexer_Index_Call) RunAndReturn(run func(path string) error) *MockIndexer_Index_Call {
	_c.Call.Return(run)
	return _c
}
