// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_server

import (
	"github.com/AvengeMedia/danksearch/internal/config"
	"github.com/AvengeMedia/danksearch/internal/indexer"
	"github.com/blevesearch/bleve/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIndexerInterface creates a new instance of MockIndexerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIndexerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIndexerInterface {
	mock := &MockIndexerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIndexerInterface is an autogenerated mock type for the IndexerInterface type
type MockIndexerInterface struct {
	mock.Mock
}

type MockIndexerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIndexerInterface) EXPECT() *MockIndexerInterface_Expecter {
	return &MockIndexerInterface_Expecter{mock: &_m.Mock}
}

// ListFiles provides a mock function for the type MockIndexerInterface
func (_mock *MockIndexerInterface) ListFiles(prefix string, limit int) ([]indexer.FileEntry, int, error) {
	ret := _mock.Called(prefix, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListFiles")
	}

	var r0 []indexer.FileEntry
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, int) ([]indexer.FileEntry, int, error)); ok {
		return returnFunc(prefix, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int) []indexer.FileEntry); ok {
		r0 = returnFunc(prefix, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]indexer.FileEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int) int); ok {
		r1 = returnFunc(prefix, limit)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(string, int) error); ok {
		r2 = returnFunc(prefix, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIndexerInterface_ListFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFiles'
type MockIndexerInterface_ListFiles_Call struct {
	*mock.Call
}

// ListFiles is a helper method to define mock.On call
//   - prefix string
//   - limit int
func (_e *MockIndexerInterface_Expecter) ListFiles(prefix any, limit any) *MockIndexerInterface_ListFiles_Call {
	return &MockIndexerInterface_ListFiles_Call{Call: _e.mock.On("ListFiles", prefix, limit)}
}

func (_c *MockIndexerInterface_ListFiles_Call) Run(run func(prefix string, limit int)) *MockIndexerInterface_ListFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIndexerInterface_ListFiles_Call) Return(fileEntrys []indexer.FileEntry, n int, err error) *MockIndexerInterface_ListFiles_Call {
	_c.Call.Return(fileEntrys, n, err)
	return _c
}

func (_c *MockIndexerInterface_ListFiles_Call) RunAndReturn(run func(prefix string, limit int) ([]indexer.FileEntry, int, error)) *MockIndexerInterface_ListFiles_Call {
	_c.Call.Return(run)
	return _c
}

// ReindexAll provides a mock function for the type MockIndexerInterface
func (_mock *MockIndexerInterface) ReindexAll() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReindexAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIndexerInterface_ReindexAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReindexAll'
type MockIndexerInterface_ReindexAll_Call struct {
	*mock.Call
}

// ReindexAll is a helper method to define mock.On call
func (_e *MockIndexerInterface_Expecter) ReindexAll() *MockIndexerInterface_ReindexAll_Call {
	return &MockIndexerInterface_ReindexAll_Call{Call: _e.mock.On("ReindexAll")}
}

func (_c *MockIndexerInterface_ReindexAll_Call) Run(run func()) *MockIndexerInterface_ReindexAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIndexerInterface_ReindexAll_Call) Return(err error) *MockIndexerInterface_ReindexAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIndexerInterface_ReindexAll_Call) RunAndReturn(run func() error) *MockIndexerInterface_ReindexAll_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockIndexerInterface
func (_mock *MockIndexerInterface) Search(query string, limit int) (*bleve.SearchResult, error) {
	ret := _mock.Called(query, limit)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *bleve.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int) (*bleve.SearchResult, error)); ok {
		return returnFunc(query, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int) *bleve.SearchResult); ok {
		r0 = returnFunc(query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bleve.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = returnFunc(query, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIndexerInterface_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockIndexerInterface_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - query string
//   - limit int
func (_e *MockIndexerInterface_Expecter) Search(query any, limit any) *MockIndexerInterface_Search_Call {
	return &MockIndexerInterface_Search_Call{Call: _e.mock.On("Search", query, limit)}
}

func (_c *MockIndexerInterface_Search_Call) Run(run func(query string, limit int)) *MockIndexerInterface_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIndexerInterface_Search_Call) Return(searchResult *bleve.SearchResult, err error) *MockIndexerInterface_Search_Call {
	_c.Call.Return(searchResult, err)
	return _c
}

func (_c *MockIndexerInterface_Search_Call) RunAndReturn(run func(query string, limit int) (*bleve.SearchResult, error)) *MockIndexerInterface_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SearchAll provides a mock function for the type MockIndexerInterface
func (_mock *MockIndexerInterface) SearchAll(opts *indexer.SearchOptions) (*indexer.SearchResult, error) {
	ret := _mock.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for SearchAll")
	}

	var r0 *indexer.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*indexer.SearchOptions) (*indexer.SearchResult, error)); ok {
		return returnFunc(opts)
	}
	if returnFunc, ok := ret.Get(0).(func(*indexer.SearchOptions) *indexer.SearchResult); ok {
		r0 = returnFunc(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*indexer.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*indexer.SearchOptions) error); ok {
		r1 = returnFunc(opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIndexerInterface_SearchAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchAll'
type MockIndexerInterface_SearchAll_Call struct {
	*mock.Call
}

// SearchAll is a helper method to define mock.On call
//   - opts *indexer.SearchOptions
func (_e *MockIndexerInterface_Expecter) SearchAll(opts any) *MockIndexerInterface_SearchAll_Call {
	return &MockIndexerInterface_SearchAll_Call{Call: _e.mock.On("SearchAll", opts)}
}

func (_c *MockIndexerInterface_SearchAll_Call) Run(run func(opts *indexer.SearchOptions)) *MockIndexerInterface_SearchAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *indexer.SearchOptions
		if args[0] != nil {
			arg0 = args[0].(*indexer.SearchOptions)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIndexerInterface_SearchAll_Call) Return(searchResult *indexer.SearchResult, err error) *MockIndexerInterface_SearchAll_Call {
	_c.Call.Return(searchResult, err)
	return _c
}

func (_c *MockIndexerInterface_SearchAll_Call) RunAndReturn(run func(opts *indexer.SearchOptions) (*indexer.SearchResult, error)) *MockIndexerInterface_SearchAll_Call {
	_c.Call.Return(run)
	return _c
}

// SearchWithOptions provides a mock function for the type MockIndexerInterface
func (_mock *MockIndexerInterface) SearchWithOptions(opts *indexer.SearchOptions) (*bleve.SearchResult, error) {
	ret := _mock.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for SearchWithOptions")
	}

	var r0 *bleve.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*indexer.SearchOptions) (*bleve.SearchResult, error)); ok {
		return returnFunc(opts)
	}
	if returnFunc, ok := ret.Get(0).(func(*indexer.SearchOptions) *bleve.SearchResult); ok {
		r0 = returnFunc(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bleve.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*indexer.SearchOptions) error); ok {
		r1 = returnFunc(opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIndexerInterface_SearchWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchWithOptions'
type MockIndexerInterface_SearchWithOptions_Call struct {
	*mock.Call
}

// SearchWithOptions is a helper method to define mock.On call
//   - opts *indexer.SearchOptions
func (_e *MockIndexerInterface_Expecter) SearchWithOptions(opts any) *MockIndexerInterface_SearchWithOptions_Call {
	return &MockIndexerInterface_SearchWithOptions_Call{Call: _e.mock.On("SearchWithOptions", opts)}
}

func (_c *MockIndexerInterface_SearchWithOptions_Call) Run(run func(opts *indexer.SearchOptions)) *MockIndexerInterface_SearchWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *indexer.SearchOptions
		if args[0] != nil {
			arg0 = args[0].(*indexer.SearchOptions)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIndexerInterface_SearchWithOptions_Call) Return(searchResult *bleve.SearchResult, err error) *MockIndexerInterface_SearchWithOptions_Call {
	_c.Call.Return(searchResult, err)
	return _c
}

func (_c *MockIndexerInterface_SearchWithOptions_Call) RunAndReturn(run func(opts *indexer.SearchOptions) (*bleve.SearchResult, error)) *MockIndexerInterface_SearchWithOptions_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function for the type MockIndexerInterface
func (_mock *MockIndexerInterface) Stats() *config.IndexStats {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 *config.IndexStats
	if returnFunc, ok := ret.Get(0).(func() *config.IndexStats); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.IndexStats)
		}
	}
	return r0
}

// MockIndexerInterface_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockIndexerInterface_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockIndexerInterface_Expecter) Stats() *MockIndexerInterface_Stats_Call {
	return &MockIndexerInterface_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockIndexerInterface_Stats_Call) Run(run func()) *MockIndexerInterface_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIndexerInterface_Stats_Call) Return(indexStats *config.IndexStats) *MockIndexerInterface_Stats_Call {
	_c.Call.Return(indexStats)
	return _c
}

func (_c *MockIndexerInterface_Stats_Call) RunAndReturn(run func() *config.IndexStats) *MockIndexerInterface_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// SyncIncremental provides a mock function for the type MockIndexerInterface
func (_mock *MockIndexerInterface) SyncIncremental() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SyncIncremental")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIndexerInterface_SyncIncremental_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncIncremental'
type MockIndexerInterface_SyncIncremental_Call struct {
	*mock.Call
}

// SyncIncremental is a helper method to define mock.On call
func (_e *MockIndexerInterface_Expecter) SyncIncremental() *MockIndexerInterface_SyncIncremental_Call {
	return &MockIndexerInterface_SyncIncremental_Call{Call: _e.mock.On("SyncIncremental")}
}

func (_c *MockIndexerInterface_SyncIncremental_Call) Run(run func()) *MockIndexerInterface_SyncIncremental_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIndexerInterface_SyncIncremental_Call) Return(err error) *MockIndexerInterface_SyncIncremental_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIndexerInterface_SyncIncremental_Call) RunAndReturn(run func() error) *MockIndexerInterface_SyncIncremental_Call {
	_c.Call.Return(run)
	return _c
}
