// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_api

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockWatcherInterface creates a new instance of MockWatcherInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatcherInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatcherInterface {
	mock := &MockWatcherInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWatcherInterface is an autogenerated mock type for the WatcherInterface type
type MockWatcherInterface struct {
	mock.Mock
}

type MockWatcherInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatcherInterface) EXPECT() *MockWatcherInterface_Expecter {
	return &MockWatcherInterface_Expecter{mock: &_m.Mock}
}

// IsRunning provides a mock function for the type MockWatcherInterface
func (_mock *MockWatcherInterface) IsRunning() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRunning")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockWatcherInterface_IsRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRunning'
type MockWatcherInterface_IsRunning_Call struct {
	*mock.Call
}

// IsRunning is a helper method to define mock.On call
func (_e *MockWatcherInterface_Expecter) IsRunning() *MockWatcherInterface_IsRunning_Call {
	return &MockWatcherInterface_IsRunning_Call{Call: _e.mock.On("IsRunning")}
}

func (_c *MockWatcherInterface_IsRunning_Call) Run(run func()) *MockWatcherInterface_IsRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWatcherInterface_IsRunning_Call) Return(b bool) *MockWatcherInterface_IsRunning_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockWatcherInterface_IsRunning_Call) RunAndReturn(run func() bool) *MockWatcherInterface_IsRunning_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockWatcherInterface
func (_mock *MockWatcherInterface) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWatcherInterface_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockWatcherInterface_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockWatcherInterface_Expecter) Start() *MockWatcherInterface_Start_Call {
	return &MockWatcherInterface_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockWatcherInterface_Start_Call) Run(run func()) *MockWatcherInterface_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWatcherInterface_Start_Call) Return(err error) *MockWatcherInterface_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWatcherInterface_Start_Call) RunAndReturn(run func() error) *MockWatcherInterface_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockWatcherInterface
func (_mock *MockWatcherInterface) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWatcherInterface_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockWatcherInterface_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockWatcherInterface_Expecter) Stop() *MockWatcherInterface_Stop_Call {
	return &MockWatcherInterface_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockWatcherInterface_Stop_Call) Run(run func()) *MockWatcherInterface_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWatcherInterface_Stop_Call) Return(err error) *MockWatcherInterface_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWatcherInterface_Stop_Call) RunAndReturn(run func() error) *MockWatcherInterface_Stop_Call {
	_c.Call.Return(run)
	return _c
}
